name: waste_collection_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  datetime_picker_formfield: ^1.0.0
  flutter_map: ^0.9.0
  material_design_icons_flutter: ^4.0.5245
  sqflite: ^1.3.0+1
  flutter_svg: ^0.17.4
  image_picker: ^0.6.6+1
  firebase_storage: ^3.1.5
  shared_preferences: ^0.5.7+2
  http: ^0.12.1
  syncfusion_flutter_charts: ^18.1.54

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pet.jpg
    - assets/papel.jpg
    - assets/vidrio.jpg
    - assets/carton.jpg
    - assets/metal.jpg
    - assets/arrows.svg
    - assets/bag.svg
    - assets/profession.svg
    - assets/ecology.svg
    - assets/clothes.svg
    - assets/frying-pan.svg
    - assets/paper.svg
    - assets/plastic.svg
    - assets/vodka.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
